# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bun Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Run lint check
      - name: Run lint check
        run: bun run lint
      
      # Run tests
      - name: Run tests
        env:
          YOUTRACK_BASE_URL: ${{ secrets.YOUTRACK_BASE_URL }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
        run: bun run test
      